stages:
  - build

variables:
  GIT_STRATEGY: clone
  GIT_CHECKOUT: "false"
  BUILD_COMMIT: $CI_COMMIT_SHORT_SHA
  BUILD_BRANCH: $CI_COMMIT_REF_NAME
  BUILD_BRANCH_SAFE: $CI_COMMIT_REF_SLUG
  BUILD_TAG: $CI_COMMIT_TAG
  BUILD_NUMBER: $CI_PIPELINE_ID
  GITHUB_OWNER: mysteriumnetwork
  GITHUB_REPO: terms

  GO_PACKAGE: github.com/mysteriumnetwork/terms
  GIT_CLONE_PATH: /home/gitlab-runner/go/src/$GO_PACKAGE
  GOFLAGS: "-count=1" # Supersedes GOCACHE=off, see: https://github.com/golang/go/issues/29378#issuecomment-449383809

generate:
  stage: build
  tags: [go]
  before_script:
    - git remote add upstream https://github.com/mysteriumnetwork/terms.git
    - git checkout -B master origin/master
    - dep ensure -v
  script: go run mage.go -v ci
  only:
    - master