stages:
  - build

variables:
  GIT_STRATEGY: clone
  BUILD_COMMIT: $CI_COMMIT_SHORT_SHA
  BUILD_BRANCH: $CI_COMMIT_REF_NAME
  BUILD_BRANCH_SAFE: $CI_COMMIT_REF_SLUG
  BUILD_TAG: $CI_COMMIT_TAG
  BUILD_NUMBER: $CI_PIPELINE_ID
  GITHUB_OWNER: mysteriumnetwork
  GITHUB_REPO: terms

generate:
  stage: build
  tags: [go]
  before_script:
    - dep ensure -v
  script: go run mage.go -v ci
  only:
    - master